name: New commit for master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_test:

    runs-on: ubuntu-latest
    env:
      VERSION_TAG: 0.1.0-preview3
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore ./Gundi
      - name: Build
        run: dotnet build ./Gundi -c Release --no-restore
      - name: Test
        run: dotnet test ./Gundi -c Release --no-build --verbosity normal
      - name: Pack
        run: dotnet pack ./Gundi -c Release --no-build -o ./artifacts -p:Version=${VERSION_TAG:1}
      - name: Nuget push
        #run: dotnet nuget push ./artifacts/Gundi.${VERSION_TAG:1}.nupkg --source nuget.org --api-key ${{secrets.NUGET_TOKEN}} --skip-duplicate
        run: ls ./artifacts
