name: Release
on:
  push:
  release:
    types: [created, unpublished, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: print release tag
        run: echo "The version of a env is $VERSION_TAG"
        env:
          VERSION_TAG: v0.1.0-preview3 #${{ github.event.release.tag_name }}