name: Release
on:
  release: 
    types: [created, unpublished, edited]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: print release tag
        run: echo ${{ github.event.release.tag_name }}