name: Release
on:
  push:
  release:
    types: [created, unpublished, edited]

jobs:
  build & test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore ./Gundi
      - name: Build
        run: dotnet build ./Gundi --no-restore
      - name: Test
        run: dotnet test ./Gundi --no-build --verbosity normal
  release:

    runs-on: ubuntu-latest

    steps:
      - name: print release tag
        run: echo "The version of a env is ${VERSION_TAG:1}"
        env:
          VERSION_TAG: v0.1.0-preview3 #${{ github.event.release.tag_name }}